POST http://localhost:5000/ HTTP/1.1

Content-Type: application/json

GET http://localhost:5000/ HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNzQxYjY2OWJkMmQ5MTcyMTg4MWM5YyIsImlhdCI6MTYzNTA2NDU0NCwiZXhwIjoxNjM1MDY0NTQ0fQ.1JIPj2J-hrIfpwI8sBpx4uFCCbIZDPveOM7EpXEe27Y